import {
  BadgeCheck,
  BellRing,
  BookOpenText,
  CalendarClock,
  ChevronRight,
  CircleEllipsis,
  Compass,
  Cross,
  Droplets,
  FileCheck2,
  FileText,
  Flame,
  HeartHandshake,
  Home,
  Infinity,
  Leaf,
  LockKeyhole,
  Mail,
  Megaphone,
  Menu,
  MessageCircle,
  MessagesSquare,
  Mountain,
  Phone,
  Rows3,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  UserRound,
  X,
} from "lucide-react";

const ICONS = {
  BadgeCheck,
  BellRing,
  BookOpenText,
  CalendarClock,
  ChevronRight,
  CircleEllipsis,
  Compass,
  Cross,
  Droplets,
  FileCheck2,
  FileText,
  Flame,
  HeartHandshake,
  Home,
  Infinity,
  Leaf,
  LockKeyhole,
  Mail,
  Megaphone,
  Menu,
  MessageCircle,
  MessagesSquare,
  Mountain,
  Phone,
  Rows3,
  Settings,
  ShieldCheck,
  ShoppingBag,
  Sparkles,
  UserRound,
  X,
};

export function AppIcon({ name, size = 20, className, strokeWidth = 2 }) {
  const Icon = ICONS[name] ?? Sparkles;

  return <Icon aria-hidden="true" className={className} size={size} strokeWidth={strokeWidth} />;
}
